### ISSUE TITLE
Tower docs audit and consolidation

### ISSUE THREAD

**Issue by llewellyn-sl** [seqeralabs/nf-tower-docs#352]
### Audit

Audit existing doc pages for adherence to the content style guide and consistent use of style elements. Update the content style guide where necessary. (@justinegeffen to detail ground rules below and update style guide)

### Consolidation

Group superfluous pages and subsections together, ensuring nesting of no more than 3 levels in IA. This is already in progress — these sections remain:

#### Monitoring — @jason-seqera 
- Consolidate dashboard, all runs, and run detail pages where possible
- Consolidate and improve metrics, load, stats where possible

#### Administration — @justinegeffen 
- Consolidate Organizations, Workspaces, and Users for a more intuitive overview. 

#### FAQs and troubleshooting — @llewellyn-sl 
- Clean up FAQs, port to evergreen where relevant 
```[tasklist]
### Tasks
- [ ] https://github.com/seqeralabs/nf-tower-docs/issues/446
- [ ] https://github.com/seqeralabs/nf-tower-docs/issues/454
- [ ] https://github.com/seqeralabs/nf-tower-docs/issues/455
- [ ] https://github.com/seqeralabs/nf-tower-docs/issues/456
- [ ] https://github.com/seqeralabs/nf-tower-docs/issues/450
- [ ] https://github.com/seqeralabs/nf-tower-docs/issues/447
- [ ] https://github.com/seqeralabs/nf-tower-docs/issues/457
- [ ] https://github.com/seqeralabs/nf-tower-docs/issues/448
- [ ] https://github.com/seqeralabs/nf-tower-docs/issues/451
- [ ] https://github.com/seqeralabs/nf-tower-docs/issues/449
- [ ] https://github.com/seqeralabs/nf-tower-docs/issues/452
- [ ] https://github.com/seqeralabs/nf-tower-docs/issues/453
- [ ] https://github.com/seqeralabs/nf-tower-docs/issues/459
```

**Comment by jason-seqera** [comment]
@llewellyn-sl, when you say _Consolidate k8s, EKS, and GKE pages into one_, what did you have in mind? Thanks!

The existing content I found:

Installation guide > Prerequisites > GCP > [GKE cluster (Kubernetes)](https://help.tower.nf/23.2/enterprise/prerequisites/gcp/#gke-cluster-kubernetes)
Installation guide > Prerequisites > AWS > [EKS cluster (Kubernetes)](https://help.tower.nf/23.2/enterprise/prerequisites/aws/#eks-cluster-kubernetes)
Installation guide > Prerequisites > AKS > [AKS cluster (Kubernetes)](https://help.tower.nf/23.2/enterprise/prerequisites/azure/#aks-cluster-kubernetes)

Installation guide > Installation > [Kubernetes](https://help.tower.nf/23.2/enterprise/kubernetes/)

User guide > Compute > Cloud providers > [Kubernetes](https://help.tower.nf/23.2/compute-envs/k8s/)
User guide > Compute > Cloud providers > [Amazon EKS](https://help.tower.nf/23.2/compute-envs/eks/)
User guide > Compute > Cloud providers > [Google GKE](https://help.tower.nf/23.2/compute-envs/gke/)

FAQs and troubleshooting > [Kubernetes](https://help.tower.nf/23.2/faqs/#kubernetes)

**Comment by llewellyn-sl** [comment]
>when you say Consolidate k8s, EKS, and GKE pages into one, what did you have in mind?

@jason-seqera I realize this overlaps with the separate k8s overhaul task on the education plan. I would say that consolidating the compute environments is less important than the accuracy and consistency of the individual pages. So, let's consider this auditing task first, and if consolidation of these pages still makes sense once the content is clean, we tackle that after. We may find that combining the K8s-based CE pages makes less sense in practice due to the number of caveats and admonitions we'd need to add to group the three different CEs into a single page. 

Let me know your thoughts.

**Comment by jason-seqera** [comment]
> > when you say Consolidate k8s, EKS, and GKE pages into one, what did you have in mind?
> 
> @jason-seqera I realize this overlaps with the separate k8s overhaul task on the education plan. I would say that consolidating the compute environments is less important than the accuracy and consistency of the individual pages. So, let's consider this auditing task first, and if consolidation of these pages still makes sense once the content is clean, we tackle that after. We may find that combining the K8s-based CE pages makes less sense in practice due to the number of caveats and admonitions we'd need to add to group the three different CEs into a single page.
> 
> Let me know your thoughts.

From what I've seen, there are enough platform/provider specific content for each Kubernetes service that this probably needs to remain separate. Thanks!

**Comment by justinegeffen** [comment]
@llewellyn-sl and I had a great chat about the tenets of the audit and areas of focus. I've updated the style guide to reflect our discussion. Take a look at the Language and style and Articles sections.

Here's an outline of what we should be looking at while we audit our sections:

- Language and natural language - natural language is easier to read and scan. It's also easier to write and less stilted. This isn't a perfect science, so it'll be good to discuss and refine this rule as we go through this.
- Contractions - Going forward, we'll use contractions in our documentation to better align with marketing.
- Headers - As we include the H1 header in the doc table, we use H2 and H3 headers in the body. 
- Gerunds - Going forward, we won't use gerunds in headers. This is for better readability and because the content we write is task-based, which the user controls rather than out of the user's control. This is outlined in the style guide.
- Front-load content - When providing instructions, provide the task upfront, followed by the process.

Some things to bear in mind:
- As we progress through this, think of ways that we can apply improvements to the UI and product experience. In many cases, the instructions/content we provide would work better as UI text to allow the user to succeed without having to read the docs. If you spot cases like this, make a note of it. 
- One of our long-term goals is to move away from instruction lists and into content where users can apply recipes to their use case. If you come across any stand-out examples where we can provide a "knowledge application" body of content, please note it down! :) 
- Search terms are an important part of documentation as are words users use. We don't have a lot of data on this yet for the docs so If you do spot inconsistencies in how we refer to things and actions, please take note. 

@llewellyn-sl, PLMK if I missed anything!

**Comment by llewellyn-sl** [comment]
@justinegeffen this is great, thank you! 

We should also apply "Front-load content" on a full-page scope. The most important information and instructions come first, with edge cases and advanced options later in the page.

**Comment by llewellyn-sl** [comment]
Also, for referring users to pages with more information, let's standardize on "See [Topic](../path/to/topic.md)". The docs currently have "Refer to", "Reference", "Go to", etc.

**Comment by llewellyn-sl** [comment]
Let's avoid using "you can" excessively. There are cases where it's needed, but in general, something like 

> You can access the configuration file templates needed for your deployment.

should be changed to 

> Access the configuration file templates needed for your deployment.

**Comment by llewellyn-sl** [comment]
I've created a [branch](https://github.com/seqeralabs/nf-tower-cloud/tree/docs-audit-epic) to serve as the epic for these tasks. For each task, let's create branches based on the epic branch, and merge our PRs into this branch. I'll do the same for the API controller page tasks.

**Comment by justinegeffen** [comment]
Thanks for all the feedback! 

And yes, excellent idea to use a branch. 😀

**Comment by gwright99** [comment]
@justinegeffen - it would be help to get a quick tour of the style guide in the next Support meeting. I think seeing old vs new will help things sink in better for the Support team.

**Comment by justinegeffen** [comment]
Excellent point, @gwright99! We can do that.

**Comment by justinegeffen** [comment]
I've noticed we use "Navigate to" and "Go to" for the first step of processes.

I lean toward "Go to" because it's clearer but I am open to debate (and suggestions!). Thoughts?

**Comment by justinegeffen** [comment]
Discussion point:
- How to structure procedures and lists
- Should they have lead-in sentences > ensure that it's not repetition of the header
- Processes shouldn't have less than 3 steps. Less than 3 steps can be a sentence
- Punctuation in lists (inconsistent)

**Comment by llewellyn-sl** [comment]
@justinegeffen @jason-seqera +1 for the Google developer docs guide. When the dust has settled, we should add some missing documentation-specific rules to our style guide as well.

**Comment by justinegeffen** [comment]
When referring to other pages in the guide/s we use:

"See... (link)"
"Learn more ... (link)"
"Visit... (link)"

We also use "Learn more" and "Learn about" in the UI. 

I'm not opposed to any of those but we should figure out what we're telling users to do - read more information, learn about something that enhances their experience, or go to a page to learn more information. Subtle differences and quite nit-picky but I think we should choose 1 and use those in the docs and the UI depending on context. 

Here's an example:

`To allow users executing pipelines from the command-line to share their runs with a given workspace, see [deployment options](../deployment-options/#nextflow-with-tower.md)`

That wouldn't work well with "Learn more", unless we rewrite the sentence to start with "Learn more about how to allow users to execute pipelines from the command-line to share their runs with a given workspace in [deployment options](../deployment-options/#nextflow-with-tower.md).

That's too verbose imo.

Thoughts on sticking with "See"? We also need to consider how this would affect the UI copy which I know refers to "Learn more". Perhaps We can use "See" in the docs and "Learn more" in the UI because they're different processes? I'd be happy with that.

**Comment by llewellyn-sl** [comment]
@justinegeffen I've been changing most "Learn more" and "Visit" to simply "See x for more information." We can use that as the docs default, except in particular instances where that feels unnatural. 

As for UI, "Learn more [here]" doesn't feel as excessive as it does in the docs. I don't have strong feelings either way, but learn more probably works better in the UI than "see" does. 

Keen to hear other folks' inputs on this.

**Comment by Kristina-Hergott** [comment]
Hi, 

I know only about "Learn more", but we use it sparingly. We try to be explicit in CTA's as it provides the user with context. Some examples where we were pushing away from "Learn more": 
<img width="367" alt="Screenshot 2023-09-29 at 11 12 10" src="https://github.com/seqeralabs/nf-tower-docs/assets/97034044/06c6156a-9d59-40c2-ad5f-67962a0dc6fb">
(https://www.nngroup.com/articles/learn-more-links/)

I have seen "Read more" in templates, but not sure its actually in UI.

**Comment by justinegeffen** [comment]
> @justinegeffen I've been changing most "Learn more" and "Visit" to simply "See x for more information." We can use that as the docs default, except in particular instances where that feels unnatural.

That works for me.

> As for UI, "Learn more [here]" doesn't feel as excessive as it does in the docs. I don't have strong feelings either way, but learn more probably works better in the UI than "see" does.

"Learn more" is more inviting in a UI context imo, I prefer it.

**Comment by justinegeffen** [comment]
What are the thoughts about capitalizing community showcase to "Community Showcase"? The other option is "Community showcase" to maintain the sentence case it follows in the UI.

**Comment by llewellyn-sl** [comment]
Completed. https://github.com/seqeralabs/nf-tower-cloud/pull/5881
