### ISSUE TITLE
Support KB cleanup and cross-reference

### ISSUE THREAD

**Issue by llewellyn-sl** [seqeralabs/nf-tower-docs#397]
support.seqera.io knowledge base is an outdated port of Tower docs FAQ content. This KB should instead link to live docs pages for each Seqera product (single source of truth) and retain the Seqera support section (reproducible pipelines, support policy, etc.)
```[tasklist]
### Tasks
- [ ] https://github.com/seqeralabs/nf-tower-docs/issues/423
- [ ] https://github.com/seqeralabs/nf-tower-docs/issues/424
- [ ] https://github.com/seqeralabs/nf-tower-docs/issues/425
```
